#pragma once

#define I2C_HDMI_ADDRESS 0x88
	#define I2C_FIRMWARE_VERSION 0x57
	#define I2C_FIRMWARE_PAGE    0x5B
		#define I2C_FIRMWARE_PAGE_TIMINGS 0x00
		#define I2C_FIRMWARE_PAGE_EEPROM  0x01

#define I2C_HDMI_PAGE_ADDRESS 0x86
